name: static_build
# this workflow is designed to:
# 1. create a static redistributable "build" of nice123d
# 2. create an OS specific launcher executable as an obvious entry point

on: [workflow_dispatch]

env:
  UV_INSTALL_DIR: uv
  
jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [windows-latest]
        # os: [macos-13, macos-14, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out nice123d from github repo
        uses: actions/checkout@v4
      - name: Download correct python-build-standalone
        shell: bash -l {0}
        run: |
          curl -L -O https://github.com/astral-sh/python-build-standalone/releases/download/20250212/cpython-3.12.9+20250212-x86_64-pc-windows-msvc-install_only_stripped.tar.gz
          mkdir python_local
          tar -xzf cpython-3.12.9+20250212-x86_64-pc-windows-msvc-install_only_stripped.tar.gz -C python_local

          python_local/python/python.exe -m pip install uv
          python_local/python/python.exe -m uv pip install .

          touch python_local/nice123d.bat
          echo "call python\python.exe -m cadviewer" > python_local/nice123d.bat
      - name: Build launcher with go
        shell: bash -l {0}
        run: |
          go version
          cd tools/nice123d_run
          ./build.bat
          cp nice123d_run.exe ../../python_local/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nice123d-${{ matrix.os }}
          path: ./python_local

          
      # ls -lRa           
      # - name: Install the latest version of uv
      #   uses: astral-sh/setup-uv@v5
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Install nice123d from local folder
      #   run: uv pip install .
      # - name: Enumerate venv dir
      #   shell: bash --login {0}
      #   run: ls -lRa
